module.exports.admins = require('./admins')
module.exports.tables = require('./tables')
module.exports.failures = require('./failures')
module.exports.collections = require('./collections')
module.exports.tokens = require('./tokens')
module.exports.bots = require('./bots')
module.exports.upcomings = require('./upcomings')
