module.exports.admins = require('./admins')
module.exports.tables = require('./tables')
module.exports.failures = require('./failures')
module.exports.collections = require('./collections')
module.exports.bots = require('./bots')
module.exports.upcomings = require('./upcomings')
module.exports.trendings = require('./trendings')
module.exports.ethereum = require('./ethereum')
